apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/vultr-loadbalancer-protocol: "https"
    # You will need to have created a TLS Secret and pass in the name as the value
  name: elasticsearch-lb
spec:
  type: LoadBalancer
  selector:
    app: elasticsearch-es-http
  ports:
    - port: 9200
      name: "https"
