apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  http:
    service:
      spec:
        type: LoadBalancer
  version: 8.1.3
  count: 3
  elasticsearchRef:
    name: "elasticsearch"
  podTemplate:
    metadata:
      labels:
        foo: bar
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 3Gi
            cpu: 1
