apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/vultr-loadbalancer-protocol: "http"
    # You will need to have created a TLS Secret and pass in the name as the value
  name: kibana-lb
spec:
  type: LoadBalancer
  selector:
    app: kibana-kb-http
  ports:
    - port: 443
      name: "https"
